default:
  interruptible: true
  # Auto-retry jobs in case of infra failures
  retry:
    max: 1
    when:
      - 'runner_system_failure'
      - 'stuck_or_timeout_failure'
      - 'scheduler_failure'
      - 'api_failure'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  COMMON_BUILD_OPTIONS: "--prefix=/usr"

.build:
  stage: "build"
  variables:
    _DEST: "$CI_PROJECT_DIR/destdir/"
  script:
    - meson setup _build $MESON_OPTIONS
    - meson compile -C _build
    - meson test -C _build --print-errorlogs --no-stdsplit --no-rebuild
    - meson dist -C _build --no-tests

    - mkdir -p $_DEST
    - meson install -C _build --no-rebuild --destdir="$_DEST"
  after_script:
    # Cleanup the destdir and thus container volume once we are done
    - rm -rvf $_DEST
  artifacts:
    expire_in: "2 days"
    when: "always"
    paths:
      - "_build/meson-logs/"
    reports:
      junit: "_build/meson-logs/testlog.junit.xml"

build-fedora:
  extends: ".build"
  image: "fedora:41"
  variables:
    MESON_OPTIONS: "$COMMON_BUILD_OPTIONS"
    DEPENDENCIES: >-
      desktop-file-utils
      gcc
      gettext
      git
      glib2-devel
      gtk3-devel
      intltool
      meson
      xdg-user-dirs
  before_script:
    - dnf upgrade -y
    - dnf install -y --setopt=install_weak_deps=false $DEPENDENCIES

build-gnomeos:
  extends: ".build"
  image: "quay.io/gnome_infrastructure/gnome-build-meta:core-nightly"
  variables:
    MESON_OPTIONS: "$COMMON_BUILD_OPTIONS"
